# Generated by Django 5.2.4 on 2025-10-01 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=128)),
                ('host_designation', models.CharField(max_length=128)),
                ('meeting_code', models.CharField(max_length=12, unique=True)),
                ('meeting_pwd', models.CharField(max_length=12)),
                ('host_status', models.IntegerField(choices=[(0, 'Not Joined'), (1, 'Joined'), (2, 'Ended')], default=0)),
                ('started_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('designation', models.CharField(max_length=128)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='meetings.meeting')),
            ],
        ),
    ]
